spring:
  application:
    name: x-to-kafka-service
x-to-kafka-service:
  enable-mock-tweets: true
  enable-v2-tweets: false
  mock-min-tweet-length: 5
  mock-max-tweet-length: 15
  mock-sleep-ms: 5000
  x-keywords:
    - Java
    - Kotlin
    - Kafka
    - ElasticSearch
retry-config:
  initial-interval-ms: 1000
  max-interval-ms: 10000
  max-attempts: 3
  sleep-time-ms: 2000
  multiplier: 2.0
kafka-config:
  bootstrap-servers: localhost:19091, localhost:19092, localhost:19093
  schema-registry-url-key: schema.registry.url
  schema-registry-url: http://localhost:8081
  topic-name: twitter-topic
  topic-names-to-create:
    - twitter-topic
  num-of-partitions: 3
  replication-factor: 3